config/routes.rb
Rails.application.routes.draw do
  resources :batches
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :rudiments

  root 'batches#index'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
	has_many :rudiments
	belongs_to :user
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_batch, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource class: Batch

  # GET /batches
  # GET /batches.json
  def index
    if user_signed_in?
      @batches = Batch.where(user_id: current_user.id).order(:id)
    else
      @batches = Batch.where(user_id: 0).order(:id)
    end
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      @batch = Batch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      params.require(:batch).permit(:user_id, :rudiment_number, :ability_bpm, :ability_beat, :endurance_bpm, :endurance_beat)
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_batchSet.html.erb
<tr id="<%= batch.id %>">
  <td style="text-align:center" class="col-md-1"><%= batch.rudiment_number %></td>

  <td class="col-md-4">
    <%= Rudiment.find(batch.rudiment_number).name %>
    <i class="fa fa-video-camera" data-src="https://www.youtube.com/embed/Z89YwuvVeYo" frameborder="0"></i>
  </td>

  <td style="text-align:center" class="col-md-2">
    <span class="ability_bpm">
      <%= batch.ability_bpm %>
    </span>
  </td>

  <td class="col-md-1">
    <div class="modify_ab" style="text-align: left">
      <div class="row">
        <i class="fa fa-plus-circle mod_metrics" id="modify_ab_plus"></i> 
      </div>
      <div class="row">
        <i class="fa fa-minus-circle mod_metrics" id="modify_ab_minus"></i> 
      </div>
    </div>
  </td>

  <td style="text-align:center" class="col-md-2">
    <div class="endurance_bpm"><%= batch.endurance_bpm %></span>
  </td>

  <td class="col-md-1">
    <div class="modify_end" style="text-align: left">
      <div class="row">
        <i class="fa fa-plus-circle mod_metrics" id="modify_end_plus"></i> 
      </div>
      <div class="row">
        <i class="fa fa-minus-circle mod_metrics" id="modify_end_minus"></i> 
      </div>
    </div>
  </td>
</tr>

app/views/batches/_form.html.erb
<%= form_for(@batch) do |f| %>
  <% if @batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% @batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :rudiment_number %><br>
    <%= f.text_field :rudiment_number %>
  </div>
  <div class="field">
    <%= f.label :ability_bpm %><br>
    <%= f.number_field :ability_bpm %>
  </div>
  <div class="field">
    <%= f.label :ability_beat %><br>
    <%= f.text_field :ability_beat %>
  </div>
  <div class="field">
    <%= f.label :endurance_bpm %><br>
    <%= f.number_field :endurance_bpm %>
  </div>
  <div class="field">
    <%= f.label :endurance_beat %><br>
    <%= f.text_field :endurance_beat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form' %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<% unless user_signed_in? %>
  <div class="col-md-8 col-md-offset-2">
    <div class="tagline">Track your rudiments. Tame those drums.</div>
    <div class="tagline_desc">Rudimentor helps you record your ability and endurance on each of the 40 drum rudiments</div><br/>
  </div>
<% else %>
  <h1>My Rudiments</h1>
<% end %>

<div class="col-md-8 col-md-offset-2">

  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="setOne">
        <h4 class="panel-title">
          <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Set I
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="setOne">
        <div class="panel-body">
          <table class="table table-striped table-responsive">
            <tbody>
              <% @batches.limit(10).each do |batch| %>
                <%= render(partial: "batches/batchSet", locals: {:batch => batch}) %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <% if user_signed_in? %>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="setTwo">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Set II
            </a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="setTwo">
          <div class="panel-body">
            <table class="table table-striped table-responsive">
              <tbody>
                <% @batches.limit(10).offset(10).each do |batch| %>
                  <%= render(:partial => "batches/batchSet", :locals => {:batch => batch}) %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="setThree">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              Set III
            </a>
          </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="setThree">
          <div class="panel-body">
            <table class="table table-striped table-responsive">
              <tbody>
                <% @batches.limit(10).offset(20).each do |batch| %>
                  <%= render(:partial => "batches/batchSet", :locals => {:batch => batch}) %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="setFour">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
              Set IV
            </a>
          </h4>
        </div>
        <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="setFour">
          <div class="panel-body">
            <table class="table table-striped table-responsive">
              <tbody>
                <% @batches.limit(10).offset(30).each do |batch| %>
                  <%= render(:partial => "batches/batchSet", :locals => {:batch => batch}) %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
    </div>

  <!-- Video Modal -->
  <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Watch and learn</h4>
        </div>
        <div class="modal-body">
          <iframe width="560" height="315" frameborder="0"></iframe>
        </div>
      </div>
    </div>
  </div>
  <br/>

</div>

<% unless user_signed_in? %>
  <div class="cta row col-md-8 col-md-offset-2">
    <center>
      Watch the video, track your progress and master your technique.<br/>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success' %> and get started on all rudiments. And yes, its completely <strong><em>free!<em></strong><br/>
      Remember, 'What gets measured, gets done'.
    </center>
  </div>
<% end %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form' %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p>
  <strong>User:</strong>
  <%= @batch.user_id %>
</p>

<p>
  <strong>Rudiment number:</strong>
  <%= @batch.rudiment_number %>
</p>

<p>
  <strong>Ability bpm:</strong>
  <%= @batch.ability_bpm %>
</p>

<p>
  <strong>Ability beat:</strong>
  <%= @batch.ability_beat %>
</p>

<p>
  <strong>Endurance bpm:</strong>
  <%= @batch.endurance_bpm %>
</p>

<p>
  <strong>Endurance beat:</strong>
  <%= @batch.endurance_beat %>
</p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>