config/routes.rb
Rails.application.routes.draw do
  resources :batches
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :rudiments

  root 'batches#index'

end

app/models/rudiment.rb
class Rudiment < ActiveRecord::Base
	belongs_to :batch
end

app/controllers/rudiments_controller.rb
class RudimentsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_rudiment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource class: Rudiment, except: :show

  # GET /rudiments
  # GET /rudiments.json
  def index
    @rudiments = Rudiment.all.order(:id)
  end

  # GET /rudiments/1
  # GET /rudiments/1.json
  def show
    respond_to do |format|
      format.json { render :json => @rudiment }
      format.html {
        authenticate_user!
        authorize! :manage, Rudiment
        render :index
      }
    end
  end

  # GET /rudiments/new
  def new
    @rudiment = Rudiment.new
  end

  # GET /rudiments/1/edit
  def edit
  end

  # POST /rudiments
  # POST /rudiments.json
  def create
    @rudiment = Rudiment.new(rudiment_params)

    respond_to do |format|
      if @rudiment.save
        format.html { redirect_to @rudiment, notice: 'Rudiment was successfully created.' }
        format.json { render :show, status: :created, location: @rudiment }
      else
        format.html { render :new }
        format.json { render json: @rudiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rudiments/1
  # PATCH/PUT /rudiments/1.json
  def update
    respond_to do |format|
      if @rudiment.update(rudiment_params)
        format.html { redirect_to @rudiment, notice: 'Rudiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @rudiment }
      else
        format.html { render :edit }
        format.json { render json: @rudiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rudiments/1
  # DELETE /rudiments/1.json
  def destroy
    @rudiment.destroy
    respond_to do |format|
      format.html { redirect_to rudiments_url, notice: 'Rudiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rudiment
      @rudiment = Rudiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rudiment_params
      params.require(:rudiment).permit(:number, :name, :yt, :sheet)
    end
end

app/helpers/rudiments_helper.rb
module RudimentsHelper
end

app/views/rudiments/_form.html.erb
<%= form_for(@rudiment) do |f| %>
  <% if @rudiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rudiment.errors.count, "error") %> prohibited this rudiment from being saved:</h2>

      <ul>
      <% @rudiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :yt %><br>
    <%= f.text_field :yt %>
  </div>
  <div class="field">
    <%= f.label :sheet %><br>
    <%= f.text_field :sheet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rudiments/edit.html.erb
<h1>Editing Rudiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @rudiment %> |
<%= link_to 'Back', rudiments_path %>

app/views/rudiments/index.html.erb
<h1>Listing Rudiments</h1>

<table class="table table-responsive table-bordered">
  <thead>
    <tr>
      <th>Number</th>
      <th>Name</th>
      <th>Youtube Video</th>
      <th>Sheet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rudiments.each do |rudiment| %>
      <tr>
        <td><%= rudiment.number %></td>
        <td><%= rudiment.name %></td>
        <td><%= rudiment.yt %></td>
        <td><%= rudiment.sheet %></td>
        <td><%= link_to 'Show', rudiment %></td>
        <td><%= link_to 'Edit', edit_rudiment_path(rudiment) %></td>
        <td><%= link_to 'Destroy', rudiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rudiment', new_rudiment_path %>

app/views/rudiments/new.html.erb
<h1>New Rudiment</h1>

<%= render 'form' %>

<%= link_to 'Back', rudiments_path %>

app/views/rudiments/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @rudiment.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @rudiment.name %>
</p>

<p>
  <strong>Yt:</strong>
  <%= @rudiment.yt %>
</p>

<p>
  <strong>Sheet:</strong>
  <%= @rudiment.sheet %>
</p>

<%= link_to 'Edit', edit_rudiment_path(@rudiment) %> |
<%= link_to 'Back', rudiments_path %>